all:
	@echo "this is the readme.md file generated by make command" > README.md
	@echo "tittle of the project: guessinggame.sh" >> README.md
	@date >> README.md
	@wc -l < guessinggame.sh >> README.md	
	@cp README.md index.html 
	@chmod -u-w README.md
